/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prueba;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public String getGreeting4() {
        return "Hello World!";
    }
    public String getGreeting3() {
        return "Hello World!";
    }
    public String getGreeting2() {
        return "Hello World!";
    }
    public String getGreeting1() {
        return "Hello World!";
    }

    public String getGreeting10() {
        return "Hello World!";
    }
    public String getGreeting11() {
        return "Hello World!";
    }
    public String getGreeting12() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
