/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prueba;

public class Fibo {

   public int fibonacci4(int n)
    {
        if (n>1){
           return fibonacci4(n-1) + fibonacci4(n-2);  //función recursiva
        }
        else if (n==1) {  // caso base
            return 1;
        }
        else if (n==0){  // caso base
            return 0;
        }
        else{ //error
            System.out.println("Debes ingresar un tamaño mayor o igual a 1");
            return -1; 
        }
    }

    public int fibonacci3(int n)
    {
        if (n>1){
           return fibonacci3(n-1) + fibonacci3(n-2);  //función recursiva
        }
        else if (n==1) {  // caso base
            return 1;
        }
        else if (n==0){  // caso base
            return 0;
        }
        else{ //error
            System.out.println("Debes ingresar un tamaño mayor o igual a 1");
            return -1; 
        }
    }

    public int fibonacci2(int n)
    {
        if (n>1){
           return fibonacci4(n-1) + fibonacci4(n-2);  //función recursiva
        }
        else if (n==1) {  // caso base
            return 1;
        }
        else if (n==0){  // caso base
            return 0;
        }
        else{ //error
            System.out.println("Debes ingresar un tamaño mayor o igual a 1");
            return -1; 
        }
    }
}
